---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  '{{cookiecutter.project_description}}'

Parameters:
  ProjectName:
    Type: String
    Default: '{{cookiecutter.project_name}}'
    Description: Simple S3 Bucket Example

  EnvironPrefix:
    Type: String
    Default: dev
    Description: String for prefixing resources to differentiate prod/dev


Resources:

  ProjectBucket:
    Properties:
      BucketName: !Sub '${EnvironPrefix}-${ProjectName}-template-bucket'
    Type: "AWS::S3::Bucket"

Outputs:
  WebsiteURL:
    Description: Arn for bucket created by template
    Value: !GetAtt ProjectBucket.Arn
